### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by rayronvictor** [alexgorbatchev/gulp-changed-in-place#1]
When I run `$ npm install --save-dev gulp-changed-in-place` the error ` 404 Registry returned 404 for GET on https://registry.npmjs.org/gulp-changed-in-place` occurs.

![captura de tela 2015-10-28 as 09 38 25](https://cloud.githubusercontent.com/assets/1683922/10788658/b185923e-7d57-11e5-8d5a-642a2ed5b574.png)

**Comment by alexgorbatchev** [comment]
Thanks! I keep forgetting I have to specify `--registry=https://registry.npmjs.org` where I'm publishing from :) Fixed!
