### ISSUE TITLE
Utilizing changed files for multiple tasks

### ISSUE THREAD

**Issue by jrubins** [alexgorbatchev/gulp-changed-in-place#6]
I'm having an issue where I only want to run my linting and code style tasks on changed files to speed up development time.

My current setup is as follows:
```js
var gulp = require('gulp');
var changedInPlace = require('gulp-changed-in-place');
var eslint = require('gulp-eslint');
var jscs = require('gulp-jscs');

var config = {
    paths: {
        js: './app/**/*.js'
    }
}

gulp.task('jscs', function() {
    return gulp.src(config.paths.js)
        .pipe(changedInPlace())
        .pipe(jscs())
        .pipe(jscs.reporter())
        .pipe(jscs.reporter('fail'));
});

gulp.task('lint', ['jscs'], function() {
    return gulp.src(config.paths.js)
        .pipe(changedInPlace())
        .pipe(eslint())
        .pipe(eslint.format())
        .pipe(eslint.failAfterError());
});

gulp.task('js', ['lint'], function() {
    // do some stuff
});

gulp.task('watch', function() {
    gulp.watch(config.paths.js, ['js']);
});
```
The issue is probably pretty obvious. The `js` task has a dependency on the `lint` task which itself has a dependency on the `jscs` task - so the `jscs` task runs first. It accesses `changedInPlace()` which causes the cache to get updated and therefore the `changedInPlace()` call from the `lint` task doesn't think anything has changed and doesn't check the files I expect.

I'm wondering if others have had this issue and if you have any suggestions on how to accomplish what I'm after - only linting and code style checking the changed file(s) on a save.

**Comment by alexgorbatchev** [comment]
You can solve this by passing different `cache` objects as options, for example

```
gulp.task('lint', ['jscs'], function() {
    return gulp.src(config.paths.js)
        .pipe(changedInPlace({ cache: {} }))
...

gulp.task('lint', ['jscs'], function() {
    return gulp.src(config.paths.js)
        .pipe(changedInPlace({ cache: {} }))
```

This will use separate objects for caching. Let me know if that worked.

**Comment by jrubins** [comment]
So unfortunately that doesn't seem to work. Looks like doing that causes none of the files to be processed because of the following logic:
```
var currentHash = cache[file.path];
cache[file.path] = newHash;

if ((!currentHash && firstPass) || (currentHash && currentHash !== newHash)) {
  this.push(file);
}
```
When I supply the empty object for the cache option, the `file.path` entry is always undefined in the empty cache object which means that the `this.push(file);` line never gets executed. The only way to get the file added is to pass `firstPass: true` as well as the empty cache object but that defeats the benefit of using this package.

Does the above explanation make sense to you or do you think I'm missing something? Could we possibly add some kind of "defer" option to prevent the cache being updated in some situations?

**Comment by alexgorbatchev** [comment]
Passing new object each time was a mistake on my part. Cache objects should be declared, could you try something like this?

```js
const cache1 = {};
const cache2 = {};

gulp.task('lint', ['jscs'], function() {
    return gulp.src(config.paths.js)
        .pipe(changedInPlace({ cache: cache1 }))
...

gulp.task('lint', ['jscs'], function() {
    return gulp.src(config.paths.js)
        .pipe(changedInPlace({ cache: cache2 }))
```
