### ISSUE TITLE
Checking for changes accross teams

### ISSUE THREAD

**Issue by RehanSaeed** [alexgorbatchev/gulp-changed-in-place#7]
I want to use gulp-imagemin which is a very slow and processor intensive task and I am working in a team environment using Git. How can I make sure that an image is only ever processed once in my entire team? Where does gulp-changed-in-place save it's change log? Can it be checked-in to Git?

**Comment by alexgorbatchev** [comment]
The `changedInPlace` takes a `{ cache: {} }` option. I think you should be able to JSON stringify the cache object at the end and write it to disk. Another option is to just generate the cache object at the start, which is just a SHA1 of the content, if you look at the source you can see that the structure is very simple and you should be able to recreate that. Does that help?

**Comment by RehanSaeed** [comment]
I think that's a great solution.

**Comment by marcamos** [comment]
@RehanSaeed Did you end up doing this, successfully? I'm in the same boat as you and not 100% certain I know how to do what you've described. Any chance you could share a simplified example?

**Comment by RehanSaeed** [comment]
@marcamos I looked into Gulp 4.0 which comes with a caching function built into it which may be able to handle this situation. I've been waiting for Gulp 4.0 to be released but it's been taking longer than I thought.

**Comment by marcamos** [comment]
@RehanSaeed Aha! Good to know, thank you.
