### ISSUE TITLE
provide TypeScript definitions for this library

### ISSUE THREAD

**Issue by atsu85** [alexgorbatchev/gulp-changed-in-place#9]
Having TypeScript definitions file makes using this library more convenient when writing gulp scripts with [TypeScript](http://www.typescriptlang.org)

**Comment by alexgorbatchev** [comment]
how do you feel about submitting a PR? i'd love to add this

**Comment by atsu85** [comment]
Hi, I've been away from front-end development for very long and now that i'm back doing a bit FE, i'm using WebPack instead - so i guess someone else might want to solve it instead
